version: '3.9'
services:
  app:
    build:
      ./build/app
    ports:
      - "8880:8880"
    user: root
    volumes:
      - type: bind
        source: ./src
        target: /src
    command: "jupyter lab --allow-root --ip=0.0.0.0 --port=8880 --no-browser --notebook-dir=/src"